/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getData } from '../fn/operations/get-data';
import { GetData$Params } from '../fn/operations/get-data';
import { SimpleEntity } from '../models/simple-entity';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getData()` */
  static readonly GetDataPath = '/v1/angular-base';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getData()` instead.
   *
   * This method doesn't expect any request body.
   */
  getData$Response(params: GetData$Params, context?: HttpContext): Observable<StrictHttpResponse<SimpleEntity>> {
    return getData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getData(params: GetData$Params, context?: HttpContext): Observable<SimpleEntity> {
    return this.getData$Response(params, context).pipe(
      map((r: StrictHttpResponse<SimpleEntity>): SimpleEntity => r.body)
    );
  }

}
