/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Problem } from './models/problem';
export type { SimpleEntity } from './models/simple-entity';
