worker_processes  1;
pid /tmp/nginx.pid;

events {
  worker_connections  1024;
}

http {
  server {
    listen 8080;
    server_name  localhost;

    root   /etc/nginx/app;
    index  index.html index.htm;
    include /etc/nginx/mime.types;

    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    location /nexus/ {
      # keep trailing slash, otherwise url rewrite does not work
      proxy_pass https://nexus.olb.de:8443/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade ${DOLLAR}http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host ${DOLLAR}host;
    }

    location /oauth2 {
      proxy_pass http://olb-angular-olbangularbasedemobackend-v1.olb-angular-olbangularbasedemobackend.svc.cluster.local:8080/oauth2;
      proxy_http_version 1.1;
      proxy_set_header Upgrade ${DOLLAR}http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host ${DOLLAR}host;
    }

    location /login/oauth2 {
      proxy_pass http://olb-angular-olbangularbasedemobackend-v1.olb-angular-olbangularbasedemobackend.svc.cluster.local:8080/login/oauth2;
      proxy_http_version 1.1;
      proxy_set_header Upgrade ${DOLLAR}http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host ${DOLLAR}host;
    }

    location /api/ {
      proxy_pass http://olb-angular-olbangularbasedemobackend-v1.olb-angular-olbangularbasedemobackend.svc.cluster.local:8080/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade ${DOLLAR}http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host ${DOLLAR}host;
    }
    
    location / {
      if (${DOLLAR}http_user_agent ~* "(kube-probe).*" ) {
        access_log off;
      }
      try_files ${DOLLAR}uri ${DOLLAR}uri/ /index.html;
    }

    location ~ /index.html {
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0'; # no cache
    }
  }
}
