/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Problem {

  /**
   * DE: Eine menschenlesbare Erklärung bezogen auf das konkrete Auftreten des Problems.<br> EN: A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;

  /**
   * DE: Liste von Fehlern die zu diesem Problem gehören.<br> EN: List of errors that belong to this problem.
   */
  errors?: Array<string>;

  /**
   * DE: Hash-Wert zum Nachvollziehen des Urpsungs des aktuellen Problems.<br> EN: hash value representing the origin of this specific problem.
   */
  hash?: string;

  /**
   * DE: Eine URI Referenz die zum Auftreten des aktuellen Problems geführt hat.<br> EN: A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;

  /**
   * DE: Der durch den ursprünglichen Server generierte HTTP-Status-Code für dieses Auftreten des Problems.<br> EN: The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status?: number;

  /**
   * DE: Eine kurze, für Menschen lesbare Zusammenfassung des Problems<br> EN: A short, human-readable summary of the problem.
   */
  title?: string;
}
